### ISSUE TITLE
numpy build failed

### ISSUE THREAD

**Issue by chestercheng** [solvcon/devenv#117]
* numpy version: [f589407](https://github.com/numpy/numpy/tree/f589407142f37c94f27c6dbe622b764e30a47c35)
* error:
    ```
    RuntimeError: Missing `SVML` submodule! Run `git submodule update --init` to fix this.
    ```

**Comment by yungyuc** [comment]
@chestercheng could you evaluate if #130 is a reasonable solution (or workaround)?

**Comment by chestercheng** [comment]
it still failed with `SRCSYNC=git`. :(
