### ISSUE TITLE
Move the script files outside the root directory

### ISSUE THREAD

**Issue by yungyuc** [solvcon/devenv#13]
I don't think we should leave script files in the root directory.

Also, we would need a simple document to tell users how to use the tool.

**Comment by yungyuc** [comment]
@tai271828 @j8xixo12 @chestercheng any thoughts?

**Comment by j8xixo12** [comment]
In my opinion, where to leave script files should let the user decide?

**Comment by yungyuc** [comment]
> In my opinion, where to leave script files should let the user decide?

Agree.  But at the moment we have four executable script files in the repository root:

```console
build-pybind11-in-conda.sh*
conda.sh*
devenv-cli.sh*
prepare-solvcon-dev.sh*
```

If staying there, they will be mixed with script files added by users.  The mixture may discourage users from placing script files in the root directory, and thus limit their options.

What should we do with **our** script files?

**Comment by tai271828** [comment]
In my opinion:

1. The four scripts are orthogonal to `devenv management tool`. The four scripts are helpers to build SOLVCON and perform a simple function test. The `devenv management tool` is a in-house source package management tool (specifically built for SOLVCON)
2. The four scripts are delivered as a kick-starter, and the goal is to replace most of its dependency management by our own tool, a.k.a. `devenv management tool` currently. See https://github.com/solvcon/devenv/issues/4#issuecomment-768357055

Thus, my gut feeling shows:
1. move devenv-cli.sh to `bin`, and probably rename it with a better name.
2. more the other scripts (conda.sh ...etc. totally 3 of them) to an individual folder, e.g. `solvcon`, `application-solvcon`, or `examples/solvcon`.

**Comment by yungyuc** [comment]
> In my opinion:
> 
> 1. The four scripts are orthogonal to `devenv management tool`. The four scripts are helpers to build SOLVCON and perform a simple function test. The `devenv management tool` is a in-house source package management tool (specifically built for SOLVCON)

Agree the orthogonality and the reason.

> 2. The four scripts are delivered as a kick-starter, and the goal is to replace most of its dependency management by our own tool, a.k.a. `devenv management tool` currently. See [#4 (comment)](https://github.com/solvcon/devenv/issues/4#issuecomment-768357055)
> 

Agree.  And we should make it clear that they are so in the file organization.

> Thus, my gut feeling shows:
> 
> 1. move devenv-cli.sh to `bin`, and probably rename it with a better name.
> 2. more the other scripts (conda.sh ...etc. totally 3 of them) to an individual folder, e.g. `solvcon`, `application-solvcon`, or `examples/solvcon`.

It sounds like a plan.  Any estimate for when there will be a PR?

**Comment by tai271828** [comment]
> > In my opinion:
> > 
> > 1. The four scripts are orthogonal to `devenv management tool`. The four scripts are helpers to build SOLVCON and perform a simple function test. The `devenv management tool` is a in-house source package management tool (specifically built for SOLVCON)
> 
> Agree the orthogonality and the reason.
> 
> > 1. The four scripts are delivered as a kick-starter, and the goal is to replace most of its dependency management by our own tool, a.k.a. `devenv management tool` currently. See [#4 (comment)](https://github.com/solvcon/devenv/issues/4#issuecomment-768357055)
> 
> Agree. And we should make it clear that they are so in the file organization.
> 
> > Thus, my gut feeling shows:
> > 
> > 1. move devenv-cli.sh to `bin`, and probably rename it with a better name.
> > 2. more the other scripts (conda.sh ...etc. totally 3 of them) to an individual folder, e.g. `solvcon`, `application-solvcon`, or `examples/solvcon`.
> 
> It sounds like a plan. Any estimate for when there will be a PR?

ETA: by the up-coming Monday! (pity. the message box of github does not allow emoji?!)
