### ISSUE TITLE
Install zlib using tarball

### ISSUE THREAD

**Issue by yungyuc** [solvcon/devenv#150]
A while back I had a discussion (probably with @j8xixo12) for whether to use tarball for installing zlib.  I did not remember what was the conclusion, but for now we still pull down the source code from git: https://github.com/solvcon/devenv/blob/fb0e4943866bf117dcd2d8f53ab40b37394c90e7/scripts/build.d/zlib#L9

I think using tarball is a more efficient and stable approach for building it and we should make it the default for the package.

**Comment by j8xixo12** [comment]
I remember the conclusion of that discussion is use tarball, but forgot to modified the build script.

**Comment by yungyuc** [comment]
I see.  I am assigning this issue to you and could you please make a tarball version when there's time?
