### ISSUE TITLE
CI takes long time (5+ minutes)

### ISSUE THREAD

**Issue by j8xixo12** [solvcon/devenv#3]
The github action takes 9 minutes to finish which seems to be a bit too long.  We may want to try to reduce it later.

_Originally posted by @yungyuc in https://github.com/solvcon/devenv/issues/1#issuecomment-765343652_

**Comment by yungyuc** [comment]
The [latest run](https://github.com/solvcon/devenv/actions/runs/503661382) took 6 minutes, which I still think a bit long.  Ideally I hope we can reduce the time to be less than 5 minutes without sacrificing sensitivity and clarity.  Any thoughts?

Or are 5-10 minutes ok to us?

**Comment by tai271828** [comment]
note: I recently notice that ubuntu testing job is way faster than mac testing job. It seems conda downloading is the bottlenect of mac testing speed.

**Comment by yungyuc** [comment]
> note: I recently notice that ubuntu testing job is way faster than mac testing job. It seems conda downloading is the bottlenect of mac testing speed.

Possible solution?

**Comment by tai271828** [comment]
> > note: I recently notice that ubuntu testing job is way faster than mac testing job. It seems conda downloading is the bottlenect of mac testing speed.
> 
> Possible solution?

The first thing comes to my mind: `devenv` may not need to test the build of an application. Let me evaluate bash unittest a bit.

**Comment by tai271828** [comment]
> > > note: I recently notice that ubuntu testing job is way faster than mac testing job. It seems conda downloading is the bottlenect of mac testing speed.
> > 
> > 
> > Possible solution?
> 
> The first thing comes to my mind: `devenv` may not need to test the build of an application. Let me evaluate bash unittest a bit.

`shunit2` looks promising to me https://github.com/kward/shunit2/ as CI replacement. I will have a look of it in more details.

Original thread: https://github.com/solvcon/devenv/pull/37#discussion_r646092679

**Comment by yungyuc** [comment]
The long test script was removed with #40 and this issue of long running time has been fixed.
