### ISSUE TITLE
Support download and extract tarball

### ISSUE THREAD

**Issue by j8xixo12** [solvcon/devenv#32]
There are some situations that the computer or server not allow to access internet, user only can upload file by themself, or just easy for install prebuilt binary.
If `devenv` can support not only download by `git` but also `tarball`, and automatic check whether the package has been downloaded before, if yes, then just untar it, it would be helpful!!

**Comment by tai271828** [comment]
FYI. For "discussion", we could use this thread https://github.com/solvcon/devenv/discussions/30 .

**Comment by yungyuc** [comment]
Fixed with #34
