### ISSUE TITLE
Enhancement of `devenv show`

### ISSUE THREAD

**Issue by tai271828** [solvcon/devenv#38]
This issue tracks the follow-up enhancement of https://github.com/solvcon/devenv/pull/35 . They could be:

1. autocomplete in `scripts/init/_devenv`
2. `bin/devenv` for the usage of a new command

**Comment by yungyuc** [comment]
@YenPeiChen07 will be working on this.

**Comment by yungyuc** [comment]
@tai271828 `devenv show` autocomplete seems to be already working:

```console
$ devenv
add     build   del     launch  list    off     show    use
```

What things about autocomplete need to be done for `devenv show`?

**Comment by tai271828** [comment]
The usage is not shown. For example,

```
┌─[^_^]─[~/work-my-projects/solvcon/devenv]
  tai271828@syakaro: 6 file 48Kb
└──╼ devenv
no active flavor: $DEVENVFLAVOR not defined

Usage: devenv [command]

Description:
    Tool to manage development environment in console

Variables:
    DEVENVROOT=/home/tai271828/work-my-projects/solvcon/devenv
    DEVENVDLROOT=/home/tai271828/work-my-projects/solvcon/devenv/var/downloaded
    DEVENVFLAVOR=

Commands:
    list   - list all available environments
    use    - activate an environment
    off    - deactivate the environment
    add    - create a new environment directory
    del    - delete a existing environment directory
    build  - build a package in the active environment
    launch - launch an application

```


Adding the usage description in the section `Commands` will make the usage description more encompassing.

**Comment by yungyuc** [comment]
Please correct me if I am wrong.  The usage description does not seem to have anything to do with autocomplete.

**Comment by tai271828** [comment]
> Please correct me if I am wrong. The usage description does not seem to have anything to do with autocomplete.

No. You are right. This ticket includes two items to track. We may make it simpler by focusing on autocomplete and create another issue to track the missing descriptioin.

**Comment by tai271828** [comment]
Use this issue https://github.com/solvcon/devenv/issues/71 to track the missing description.

**Comment by tai271828** [comment]
Sounds good to me! Thanks.
