### ISSUE TITLE
Discuss the use of miniconda for installing dependencies

### ISSUE THREAD

**Issue by j8xixo12** [solvcon/devenv#4]
This script uses miniconda for most of the dependencies so I think it's probably good to highlight it in the filename.  We may do it with this PR or act after more discussions.

_Originally posted by @yungyuc in https://github.com/solvcon/devenv/pull/1#discussion_r562575371_

**Comment by tai271828** [comment]
Thanks for filing issues from the comment of #1 so fast. It is so fast that I thought it was done by some github feature. : )

**Comment by yungyuc** [comment]
Impressive.  Thanks a lot, @j8xixo12 .

**Comment by tai271828** [comment]
In my opinion, the most straightforward implementation is to build each package of conda from source one by one. At the very beginning we use conda. In the end we may build as many packages from source on our own as possible.

**Comment by yungyuc** [comment]
> In my opinion, the most straightforward implementation is to build each package of conda from source one by one. At the very beginning we use conda. In the end we may build as many packages from source on our own as possible.

That sounds like duplicating what conda forge does.

Besides, it doesn't sound like to allow multiple DEs (rel, dbg, etc.) in parallel?

**Comment by tai271828** [comment]
The discussion of https://github.com/solvcon/devenv/issues/13#issuecomment-820741629 make me recall this thread. Sorry for the late reply.

> > In my opinion, the most straightforward implementation is to build each package of conda from source one by one. At the very beginning we use conda. In the end we may build as many packages from source on our own as possible.
> 
> That sounds like duplicating what conda forge does.
I am not sure if we are on the same page. For me, it is `devenv management tool` to add/replace each packages. If `devenv management tool` could build all packages we need to launch `devenv-cli.sh` in CI, we could abandon the use of miniconda anytime.
> 
> Besides, it doesn't sound like to allow multiple DEs (rel, dbg, etc.) in parallel?

I did not follow the last question. What did you mean by "not allow multiple DEs (rel, dbg, etc.) in parallel? Why?

**Comment by yungyuc** [comment]
> The discussion of [#13 (comment)](https://github.com/solvcon/devenv/issues/13#issuecomment-820741629) make me recall this thread. Sorry for the late reply.
> 
> > > In my opinion, the most straightforward implementation is to build each package of conda from source one by one. At the very beginning we use conda. In the end we may build as many packages from source on our own as possible.
> > 
> > 
> > That sounds like duplicating what conda forge does.
> 
> I am not sure if we are on the same page. For me, it is `devenv management tool` to add/replace each packages. If `devenv management tool` could build all packages we need to launch `devenv-cli.sh` in CI, we could abandon the use of miniconda anytime.

Agree that when `devenv` builds everything we don't need conda anymore.  Conda may be left as an optional step for packages we prefer to not build, though.

> 
> > Besides, it doesn't sound like to allow multiple DEs (rel, dbg, etc.) in parallel?
> 
> I did not follow the last question. What did you mean by "not allow multiple DEs (rel, dbg, etc.) in parallel? Why?

I meant, the conda builder doesn't seem to allow building different flavors (rel/dbg).  But I am not sure.  Does it?

**Comment by tai271828** [comment]
> > The discussion of [#13 (comment)](https://github.com/solvcon/devenv/issues/13#issuecomment-820741629) make me recall this thread. Sorry for the late reply.
> > > > In my opinion, the most straightforward implementation is to build each package of conda from source one by one. At the very beginning we use conda. In the end we may build as many packages from source on our own as possible.
> > > 
> > > 
> > > That sounds like duplicating what conda forge does.
> > 
> > 
> > I am not sure if we are on the same page. For me, it is `devenv management tool` to add/replace each packages. If `devenv management tool` could build all packages we need to launch `devenv-cli.sh` in CI, we could abandon the use of miniconda anytime.
> 
> Agree that when `devenv` builds everything we don't need conda anymore. Conda may be left as an optional step for packages we prefer to not build, though.
Cool! We are on the same page : D
> 
> > > Besides, it doesn't sound like to allow multiple DEs (rel, dbg, etc.) in parallel?
> > 
> > 
> > I did not follow the last question. What did you mean by "not allow multiple DEs (rel, dbg, etc.) in parallel? Why?
> 
> I meant, the conda builder doesn't seem to allow building different flavors (rel/dbg). But I am not sure. Does it?
I see. I am not sure too. My gut feeling is "no, it doesn't".

**Comment by yungyuc** [comment]
I realize that this page here is an issue but we actually have repository discussions set up.  Let's move the discussions there: #14 .
