### ISSUE TITLE
Enable ubuntu-20.04 and macos-11 .0 in CI

### ISSUE THREAD

**Issue by yungyuc** [solvcon/devenv#5]
The current CI OS matrix (https://github.com/solvcon/devenv/blob/main/.github/workflows/solvcon_install.yml#L10) includes `ubuntu-18.04` and `macos-latest` (which is an alias to `macos-10.15`).  I would like it to include two more versions: `ubuntu-20.04` and `macos-11.0`, which are beyond the latest aliases.  The current `macos-latest` should be renamed to `macos-10.15`.

See [the github hosted runners](https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources) for more information.

**Comment by yungyuc** [comment]
@j8xixo12 would you have time to take this?

**Comment by tai271828** [comment]
> @j8xixo12 would you have time to take this?

yeah I feel like people with macOS will be better than me to enhance this feature. I noticed the turn-around time running on Ubuntu is much less than macOS. The Ubuntu turnaround time is around 3 minutes, so I think it should acceptable.

**Comment by yungyuc** [comment]
Relevant note (see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners):

> Note: The **macOS 11.0** virtual environment is currently provided as a **private preview** only. Any users or organizations that are already using this runner can continue using it, but we're not accepting any further users or organizations at this time. The macos-latest YAML workflow label still uses the macOS 10.15 virtual environment.

**Comment by j8xixo12** [comment]
Sorry for late reply.

I think I can take this.

**Comment by tai271828** [comment]
> Relevant note (see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners):
> 
> > Note: The **macOS 11.0** virtual environment is currently provided as a **private preview** only. Any users or organizations that are already using this runner can continue using it, but we're not accepting any further users or organizations at this time. The macos-latest YAML workflow label still uses the macOS 10.15 virtual environment.

What?! Are we lucky enough to launch the corresponding runner timely? Hooray!?

**Comment by yungyuc** [comment]
This is partially done and the mac runner will be tracked in #53
