### ISSUE TITLE
This repo should not depend on the SOLVCON repo

### ISSUE THREAD

**Issue by yungyuc** [solvcon/devenv#6]
Currently [SOLVCON repo](https://github.com/solvcon/solvcon) is cloned in [prepare-solvcon-dev.sh line #19](https://github.com/solvcon/devenv/blob/main/prepare-solvcon-dev.sh#L19) to make the script working.  So the SOLVCON repo circularly depends on this devenv.

We should not clone the SOLVCON repo for installing packages.

**Comment by yungyuc** [comment]
@tai271828 Comments?

**Comment by tai271828** [comment]
+1 to the proposal. We are aim at a "standalone" and isolated tool so circular dependency is not ideal. We should port the scripts which devenv needs to use (or create an new one) to make devenv not depend on SOLVCON repo.

The very first commit is used for kicking start the implementation by learning from doing before we have a clear and concrete architecture blueprint. Proposals or discussion like this issue are very welcome. Thanks for the feedback!

**Comment by yungyuc** [comment]
Assign to you and me.

**Comment by yungyuc** [comment]
This has been fixed a while back.
