### ISSUE TITLE
`launch` does not fully use pre-define `$DEVENVFLAVOR`

### ISSUE THREAD

**Issue by tai271828** [solvcon/devenv#66]
# Description
`devenv launch solvcon` does not use `$DEVENVFLAVOR` and use the hard-coded flavor name `solvcon-dev`.

# Steps to Reproduce
1. `devenv launch solvcon`. `devenv` will complain `$DEVENVFLAVOR not defined`.
1. `devenv add flavor1`
1. `devenv launch solvcon`
1. `devenv show`

# Expected Result
Only `flavor1` is listed.

# Actual Result
Both `flavor1` and `solvcon-devenv` are listed.

**Comment by tai271828** [comment]
May be here `bin/build-application-solvcon-devenv.sh:DEVENV_FLAVOR="solvcon-devenv"`

**Comment by yungyuc** [comment]
I do not have an environment use the app to test.  Should we close this issue @tai271828 ?
