### ISSUE TITLE
python 3.8 built on macOS does not function correctly

### ISSUE THREAD

**Issue by tai271828** [solvcon/devenv#83]
When building SOLVCON with python 3.8, [the corresponding CI](https://github.com/tai271828/solvcon/runs/3573960270?check_suite_focus=true) works well on Ubuntu, but not macOS.

The error messages shows

```
/Users/runner/work/solvcon/solvcon/devenv/scripts/build.d/python: line 72: /Users/runner/work/solvcon/solvcon/devenv/flavors/prime/usr/bin/python3: No such file or directory
```

# Step to Reproduce
I don't have a mac so I did not try practically, but I believe this could be reproduce by simply executing `devenv build python`:

1. Create a `devevn` flavor from scratch as usual. For example, `prime` by `devenv add prime` and then `devenv use prime`
2. `devenv build python`
3. `which python3`

# Expected Result
The real path of `python3` is shown and it's a copy of, or a symbolic link to python 3.8 binary built by `devenv`.

# Actual Result
[This SOLVCON CI job](https://github.com/tai271828/solvcon/runs/3573960270?check_suite_focus=true) shows `python3` is unavailable.

**Comment by tai271828** [comment]
I did manually create the symbolic link, and the runtime of python 3.8 is obviously unavailable or incorrect. For example, the error message from [this CI job](https://github.com/tai271828/solvcon/runs/3573890673?check_suite_focus=true):

```
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'
```

I guess this issue is similar to the gmsh one https://github.com/solvcon/devenv/issues/81

**Comment by j8xixo12** [comment]
It seems `python3` is using MacOS system SDK's `sqlite`, according to [python 3.8 setup.py](https://github.com/python/cpython/blob/07119dd38c9a6e5da84ca8a0a46acdf8a3e60ecf/setup.py#L1419)
that python3 prohibit to use system built-in sqlite and I also can reproduce on my MacBook.

**Comment by yungyuc** [comment]
> It seems `python3` is using MacOS system SDK's `sqlite`, according to [python 3.8 setup.py](https://github.com/python/cpython/blob/07119dd38c9a6e5da84ca8a0a46acdf8a3e60ecf/setup.py#L1419)
> that python3 prohibit to use system built-in sqlite and I also can reproduce on my MacBook.

I wonder what would be a resolution that you would like to propose?

**Comment by chestercheng** [comment]
> It seems `python3` is using MacOS system SDK's `sqlite`, according to [python 3.8 setup.py](https://github.com/python/cpython/blob/07119dd38c9a6e5da84ca8a0a46acdf8a3e60ecf/setup.py#L1419)
> that python3 prohibit to use system built-in sqlite and I also can reproduce on my MacBook.

is it related with [Issue10268](https://bugs.python.org/issue10268) ?

**Comment by tai271828** [comment]
I prepared sqlite build script of devenv https://github.com/tai271828/devenv/blob/dev-solvcon-ci/scripts/build.d/sqlite . Let me re-try a bit.

**Comment by tai271828** [comment]
The `setup.py` looks a bit weird. For example, this line https://github.com/python/cpython/blob/07119dd38c9a6e5da84ca8a0a46acdf8a3e60ecf/setup.py#L1337 seems to show the `setup.py` only search mac os system path for squlite?!!

> It seems `python3` is using MacOS system SDK's `sqlite`, according to [python 3.8 setup.py](https://github.com/python/cpython/blob/07119dd38c9a6e5da84ca8a0a46acdf8a3e60ecf/setup.py#L1419)
> that python3 prohibit to use system built-in sqlite and I also can reproduce on my MacBook.

**Comment by tai271828** [comment]
Thanks @chestercheng . The bug information also helps. I tried the sqlite build script of devenv, and it seems that `--enable-loadable-sqlite-extensions=no` does not work for mac as the bug  Issue10268 you shared with us.

> > It seems `python3` is using MacOS system SDK's `sqlite`, according to [python 3.8 setup.py](https://github.com/python/cpython/blob/07119dd38c9a6e5da84ca8a0a46acdf8a3e60ecf/setup.py#L1419)
> > that python3 prohibit to use system built-in sqlite and I also can reproduce on my MacBook.
> 
> is it related with [Issue10268](https://bugs.python.org/issue10268) ?

**Comment by tai271828** [comment]
According my latest study, `setup.py` for mac seems to have 2 issues for mac:
- search system path only for sqlite lib
- the option of disabling sqlite extension does not work (known issue  https://bugs.python.org/issue10268 )

**Comment by tai271828** [comment]
hmmm interesting, issue 10268 was closed and merge

```
commit 076ed00003ef0d94871d9dc070ae42c854a89718
Author: Benjamin Peterson <benjamin@python.org>
Date:   Sun Oct 31 17:11:02 2010 +0000

    add --enable-loadable-sqlite-extensions #10268
```

**Comment by tai271828** [comment]
It's very inefficient for me to debug without macOS runtime. Let me stop at proposal the merge request to build sqlite by devenv https://github.com/solvcon/devenv/pull/84 , and leave the rest study to developers with macOS. Please feel free to let me know what I can help anytime!

**Comment by j8xixo12** [comment]
@tai271828
According to https://github.com/python/cpython/blob/07119dd38c9a6e5da84ca8a0a46acdf8a3e60ecf/setup.py#L1357
python's setup.py will check the compile options and check the path if path is in `MacOS SDK root`, and GitHub workflow's MacOS also pre-install `sqlite`, so I think maybe add compile option that specified `sqlite` path may work.

I fork your solvcon repo and  added `CPPFLAGS=-I$(brew --prefix sqlite)/include LDFLAGS=-L$(brew --prefix sqlite)/lib VERSION=3.8 devenv build python` into solvcon_install.yml
https://github.com/j8xixo12/solvcon/runs/3579806387?check_suite_focus=true#step:4:21135
then python can find sqlite properly !!

**Comment by tai271828** [comment]
Man, you are my hero!

> @tai271828
> According to https://github.com/python/cpython/blob/07119dd38c9a6e5da84ca8a0a46acdf8a3e60ecf/setup.py#L1357
> python's setup.py will check the compile options and check the path if path is in `MacOS SDK root`, and GitHub workflow's MacOS also pre-install `sqlite`, so I think maybe add compile option that specified `sqlite` path may work.
> 
> I fork your solvcon repo and added `CPPFLAGS=-I$(brew --prefix sqlite)/include LDFLAGS=-L$(brew --prefix sqlite)/lib VERSION=3.8 devenv build python` into solvcon_install.yml
> https://github.com/j8xixo12/solvcon/runs/3579806387?check_suite_focus=true#step:4:21135
> then python can find sqlite properly !!

**Comment by tai271828** [comment]
The search path issue could be resolved by the CPPFLAGS and LDFLAGS tricks commented by @j8xixo12  . Besides, this sqlite build script of `devenv` could be also applied and succeed to build python https://github.com/solvcon/devenv/pull/84 .

> According my latest study, `setup.py` for mac seems to have 2 issues for mac:
> 
> * search system path only for sqlite lib
> * the option of disabling sqlite extension does not work ~(known issue  https://bugs.python.org/issue10268 )~
