### ISSUE TITLE
[app][solvcon] build-pybind11-in-conda.sh may be redundant

### ISSUE THREAD

**Issue by tai271828** [solvcon/devenv#87]
Heads-up from https://github.com/solvcon/devenv/pull/86#pullrequestreview-773352536 . We will use this issue as the story tracker.

**Comment by yungyuc** [comment]
Assign to @tai271828 for he is testing this after #91 is merged.

**Comment by tai271828** [comment]
#91 and #94 has landed. Close this issue.
