### ISSUE TITLE
[solvcon] CI fails

### ISSUE THREAD

**Issue by tai271828** [solvcon/devenv#98]
We introduce https://github.com/solvcon/devenv/pull/97 for https://github.com/solvcon/devenv/issues/92 , and I believe the pull request fails SOLVCON built by devenv in the Action runs manually triggered by me again today:

- https://github.com/solvcon/devenv/runs/4594808783?check_suite_focus=true
- https://github.com/solvcon/solvcon/runs/4594813592?check_suite_focus=true

**Comment by yungyuc** [comment]
It's fine.  I think the schedule builds do not use the new checkins.  We can wait for the next schedule to run.

**Comment by tai271828** [comment]
Next step:

Wait for the scheduled run on Friday fails to see if it fails with the same error or not.

**Comment by yungyuc** [comment]
@tai271828 Since you opened the issue, can you take a look at the next schedule time point?

**Comment by tai271828** [comment]
> It's fine. I think the schedule builds do not use the new checkins. We can wait for the next schedule to run.

Neat, we commented on the thread at the same time (and have the same point of view!)

**Comment by tai271828** [comment]
> @tai271828 Since you opened the issue, can you take a look at the next schedule time point?

Absolutely yes : )

**Comment by tai271828** [comment]
The scheduled runs showed the failures from SOLVCON and devenv repositories are caused by the same issue:
```
tar (child): SOLVCON-0.1.4+.tar.gz: Cannot open: No such file or directory
768
tar (child): Error is not recoverable: exiting now
769
tar: Child returned status 2
770
tar: Error is not recoverable: exiting now
771
/bin/bash: line 7: cd: SOLVCON-0.1.4+: No such file or directory
772
make[1]: Entering directory '/home/runner/work/solvcon/solvcon/dist'
773
make[1]: *** No targets specified and no makefile found.  Stop.
774
make[1]: Leaving directory '/home/runner/work/solvcon/solvcon/dist'
775
cd dist/SOLVCON-0.1.4+ ; \
```

By the way, it seems the naming convention of pip changes:

```
/home/runner/work/devenv/devenv/flavors/prime/usr/lib/python3.8/site-packages/setuptools/dist.py:507: UserWarning: The version specified ('0.1.4+') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
```

and AFAIK, some installation standard is changing as well recently. For example:

```
/home/runner/work/devenv/devenv/flavors/prime/usr/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
773
  warnings.warn(
774
/home/runner/work/devenv/devenv/flavors/prime/usr/lib/python3.8/site-packages/setuptools/command/egg_info.py:624: SetuptoolsDeprecationWarning: Custom 'build_py' does not implement 'get_data_files_without_manifest'.
```

**Comment by yungyuc** [comment]
Have you reproduced the failure locally?

**Comment by tai271828** [comment]
> Have you reproduced the failure locally?

Interesting, I passed the build locally (Ubuntu 20.04).

**Comment by yungyuc** [comment]
> > Have you reproduced the failure locally?
> 
> 
> 
> Interesting, I passed the build locally (Ubuntu 20.04) with the latest devenv eaac1117a9d70770a077252d4d9669ce7077a3f0 .

Thanks for the study.  I think it will be a right way to reproduce it locally and then try to fix it.

**Comment by tai271828** [comment]
More fun facts: SOLVCON installation performed with conda still works. Only installed by dev would fail[1]. However, my test earlier shows local installation (ubuntu on x86) also works https://github.com/solvcon/devenv/issues/98#issuecomment-1003438485 . It seems the configuration of Action may be the root cause.

[1] https://github.com/solvcon/solvcon/actions

**Comment by j8xixo12** [comment]
hmm… I tried to build solvcon via `devenv launch solvcon` on my local machine (arch on x86), I success install each dependencies, but I failed at building `libmarch.so`.
The following are error during build solvcon:
1. Can not find Scotch library
    `CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
SCOTCHMETIS_LIBRARY
    linked by target "libmarch" in directory /home/j8xixo12/.devenv/flavors/prime/src/solvcon-master/libmarch/src/python `

   I notice the `applications/solvcon/entry.sh` using the latest version of Scotch 
`SYNCGIT="yes" devenv build scotch `and the `libscotchmetis` has been re-name to `libscotchmetisv3.a` and `libscotchmetisv5.a`, so I tried to build **scotch** with `v6.1.0` manually, then **cmake** can find **SCOTCHMETIS_LIBRARY**
2. gcc compile option not exist
    `WARN: CCompilerOpt.dist_test[590] : CCompilerOpt._dist_test_spawn[724] : Command (gcc-7 -pthread -
Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/j8xixo12/.devenv/flav
ors/prime/usr/include/python3.8 -c /home/j8xixo12/.devenv/flavors/prime/usr/lib/python3.8/site-pac
kages/numpy/distutils/checks/test_flags.c -o /tmp/tmp2cu1cyek/home/j8xixo12/.devenv/flavors/prime/
usr/lib/python3.8/site-packages/numpy/distutils/checks/test_flags.o -MMD -MF /tmp/tmp2cu1cyek/home
/j8xixo12/.devenv/flavors/prime/usr/lib/python3.8/site-packages/numpy/distutils/checks/test_flags.
o.d -mavx512vnni) failed with exit status 1 output ->                                             
gcc-7: error: unrecognized command line option ‘-mavx512vnni’; did you mean ‘-mavx5124vnniw’? `
here is my gcc-7 info
`gcc-7 -v
Using built-in specs.
COLLECT_GCC=gcc-7
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/7.5.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /home/j8xixo12/git_repo/gcc7/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,fortran,lto --disable-multilib --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --program-suffix=-7 --enable-version-specific-runtime-libs
Thread model: posix
gcc version 7.5.0 (GCC) `

3. setuptool AttributesError
    `File "setup.py", line 167, in build_extension
    return np_build_ext.build_ext.build_extension(self, ext)
  File "/home/j8xixo12/.devenv/flavors/prime/usr/lib/python3.8/site-packages/numpy/distutils/command/build_ext.py", line 380, in build_extension    extra_cflags = ext.extra_c_compile_args or [] 
AttributeError: 'Extension' object has no attribute 'extra_c_compile_args'make: *** [Makefile:84: legacy] Error 1`

**Comment by tai271828** [comment]
Update: weird. I can't reproduce the success locally again. Maybe I made a mistake to use unexpected branches locally Orz.

> > Have you reproduced the failure locally?

> 
> Interesting, I passed the build locally (Ubuntu 20.04) with the latest devenv [eaac111](https://github.com/solvcon/devenv/commit/eaac1117a9d70770a077252d4d9669ce7077a3f0) .

**Comment by tai271828** [comment]
I have the same result today. Thanks for the summary!

> hmm… I tried to build solvcon via `devenv launch solvcon` on my local machine (arch on x86), I success install each dependencies, but I failed at building `libmarch.so`. The following are error during build solvcon:
> 
> 1. Can not find Scotch library
>    `CMake Error: The following variables are used in this project, but they are set to NOTFOUND. Please set them or make sure they are set and tested correctly in the CMake files: SCOTCHMETIS_LIBRARY linked by target "libmarch" in directory /home/j8xixo12/.devenv/flavors/prime/src/solvcon-master/libmarch/src/python `
>    I notice the `applications/solvcon/entry.sh` using the latest version of Scotch
>    `SYNCGIT="yes" devenv build scotch `and the `libscotchmetis` has been re-name to `libscotchmetisv3.a` and `libscotchmetisv5.a`, so I tried to build **scotch** with `v6.1.0` manually, then **cmake** can find **SCOTCHMETIS_LIBRARY**
> 2. gcc compile option not exist
>    `WARN: CCompilerOpt.dist_test[590] : CCompilerOpt._dist_test_spawn[724] : Command (gcc-7 -pthread - Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/j8xixo12/.devenv/flav ors/prime/usr/include/python3.8 -c /home/j8xixo12/.devenv/flavors/prime/usr/lib/python3.8/site-pac kages/numpy/distutils/checks/test_flags.c -o /tmp/tmp2cu1cyek/home/j8xixo12/.devenv/flavors/prime/ usr/lib/python3.8/site-packages/numpy/distutils/checks/test_flags.o -MMD -MF /tmp/tmp2cu1cyek/home /j8xixo12/.devenv/flavors/prime/usr/lib/python3.8/site-packages/numpy/distutils/checks/test_flags. o.d -mavx512vnni) failed with exit status 1 output ->                                              gcc-7: error: unrecognized command line option ‘-mavx512vnni’; did you mean ‘-mavx5124vnniw’? `
>    here is my gcc-7 info
>    `gcc-7 -v Using built-in specs. COLLECT_GCC=gcc-7 COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/7.5.0/lto-wrapper Target: x86_64-pc-linux-gnu Configured with: /home/j8xixo12/git_repo/gcc7/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,fortran,lto --disable-multilib --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --program-suffix=-7 --enable-version-specific-runtime-libs Thread model: posix gcc version 7.5.0 (GCC) `
> 3. setuptool AttributesError
>    `File "setup.py", line 167, in build_extension return np_build_ext.build_ext.build_extension(self, ext)   File "/home/j8xixo12/.devenv/flavors/prime/usr/lib/python3.8/site-packages/numpy/distutils/command/build_ext.py", line 380, in build_extension    extra_cflags = ext.extra_c_compile_args or []  AttributeError: 'Extension' object has no attribute 'extra_c_compile_args'make: *** [Makefile:84: legacy] Error 1`

**Comment by tai271828** [comment]
Interesting. I checked out 830335b844b8e1c274a12d38d208431e1baa1826 of devenv , which is the latest successful CI run, and failed to run with Action https://github.com/tai271828/devenv/runs/4754841130?check_suite_focus=true

Some more stuff (maybe a third party package) must change in the past month.

**Comment by tai271828** [comment]
Some more fun facts: Action failed with different error message from the most recent a.k.a. yesterday fail of Ubuntu job and the first recent fail of Ubuntu job.

For example,
- (Fact I) The 1st recent run failed for `make: *** [test_from_package] Error 1` for `NameError: name '_algorithm' is not defined` from `devevn` https://github.com/solvcon/devenv/runs/4594808783?check_suite_focus=true and `SOLVCON` https://github.com/solvcon/solvcon/runs/4594813592?check_suite_focus=true
- (Fact II) The most recent run failed for missing `SCOTCHMETIS_LIBRARY` from `devenv` https://github.com/solvcon/devenv/runs/4820829080?check_suite_focus=true and `SOLVCON` https://github.com/solvcon/solvcon/runs/4820831062?check_suite_focus=true

(Fact III) If we checked out to the same codebase of `devenv` and `SOLVCON` which provides the most recent successful run with Ubuntu AND system-wide scotch library (installed via apt), we will get the `extra_c_compile_args` error message instead.

So, my hypothesis is:
A. Per Fact III: Something changed so `distutils` does not support build_ext.py in the way we expected to cause `extra_c_compile_args` in the past 1.5 months since the last succesful CI run.
B. Per Fact II and I: Something may change the way to load lib from the other third party packages. The recent bzip2 merge is suspicious.

Next step of mine:
1. Roll back to the last codebase with successful CI run. It is a combination of `devenv` 830335b844b8e1c274a12d38d208431e1baa1826 and `SOLVCON` eaac1117a9d70770a077252d4d9669ce7077a3f0 to nail down hypothesis A first.
2. Nail down hypothesis B based on the result of the previous step.

**Comment by tai271828** [comment]
numpy version 1.21.4 to 1.21.5 is suspicious mostly to raise the missing/unsupported `extra_c_compile_args` issue for its release date, date of CI fail and the corresponding error message of CI run.

The following packages/tools are investigated and less likely the root cause of the missing/unsupported `extra_c_compile_args` issue for their release date: `pip`, `distutils`, and `cpython 3.8`.

Next step:
Pin numpy version to see if we can pin down the issue reproducer with numpy version.

> Some more fun facts: Action failed with different error message from the most recent a.k.a. yesterday fail of Ubuntu job and the first recent fail of Ubuntu job.
> 
> For example,
> 
> * (Fact I) The 1st recent (to 15 days and longer ago) run failed for `make: *** [test_from_package] Error 1` for `NameError: name '_algorithm' is not defined` from `devevn` https://github.com/solvcon/devenv/runs/4594808783?check_suite_focus=true and `SOLVCON` https://github.com/solvcon/solvcon/runs/4594813592?check_suite_focus=true
> * (Fact II) The most recent run (to 8 days and less ago)  failed for missing `SCOTCHMETIS_LIBRARY` from `devenv` https://github.com/solvcon/devenv/runs/4820829080?check_suite_focus=true and `SOLVCON` https://github.com/solvcon/solvcon/runs/4820831062?check_suite_focus=true
> 
> (Fact III) If we checked out to the same codebase of `devenv` and `SOLVCON` which provides the most recent successful run with Ubuntu AND system-wide scotch library (installed via apt), we will get the `extra_c_compile_args` error message instead.
> 
> So, my hypothesis is: A. Per Fact III: Something changed so `numpy/distutils/command/build_ext.py` does not support build_ext.py in the way we expected to cause `extra_c_compile_args` in the past 1.5 months since the last succesful CI run. B. Per Fact II and I: Something may change the way to load lib from the other third party packages. The recent bzip2 merge is suspicious.
> 
> Next step of mine:
> 
> 1. Roll back to the last codebase with successful CI run. It is a combination of `devenv` [830335b](https://github.com/solvcon/devenv/commit/830335b844b8e1c274a12d38d208431e1baa1826) and `SOLVCON` [eaac111](https://github.com/solvcon/devenv/commit/eaac1117a9d70770a077252d4d9669ce7077a3f0) to nail down hypothesis A first.
> 2. Nail down hypothesis B based on the result of the previous step.

**Comment by tai271828** [comment]
Lock `numpy==1.21.4` will help.

By locking `numpy==1.21.4`, the codebase of `devenv` 830335b , we could resume the CI with Ubuntu 20.04 (with some minor fixup for dependency packages). I will create a pull request to move this step of "hypothesis A" forward, and then investigate "hypothesis B".


> numpy version 1.21.4 to 1.21.5 is suspicious mostly to raise the missing/unsupported `extra_c_compile_args` issue for its release date, date of CI fail and the corresponding error message of CI run.
> 
> The following packages/tools are investigated and less likely the root cause of the missing/unsupported `extra_c_compile_args` issue for their release date: `pip`, `distutils`, and `cpython 3.8`.
> 
> Next step: Pin numpy version to see if we can pin down the issue reproducer with numpy version.
> 
> > Some more fun facts: Action failed with different error message from the most recent a.k.a. yesterday fail of Ubuntu job and the first recent fail of Ubuntu job.
> > For example,
> > 
> > * (Fact I) The 1st recent (to 15 days and longer ago) run failed for `make: *** [test_from_package] Error 1` for `NameError: name '_algorithm' is not defined` from `devevn` https://github.com/solvcon/devenv/runs/4594808783?check_suite_focus=true and `SOLVCON` https://github.com/solvcon/solvcon/runs/4594813592?check_suite_focus=true
> > * (Fact II) The most recent run (to 8 days and less ago)  failed for missing `SCOTCHMETIS_LIBRARY` from `devenv` https://github.com/solvcon/devenv/runs/4820829080?check_suite_focus=true and `SOLVCON` https://github.com/solvcon/solvcon/runs/4820831062?check_suite_focus=true
> > 
> > (Fact III) If we checked out to the same codebase of `devenv` and `SOLVCON` which provides the most recent successful run with Ubuntu AND system-wide scotch library (installed via apt), we will get the `extra_c_compile_args` error message instead.
> > So, my hypothesis is: A. Per Fact III: Something changed so `numpy/distutils/command/build_ext.py` does not support build_ext.py in the way we expected to cause `extra_c_compile_args` in the past 1.5 months since the last succesful CI run. B. Per Fact II and I: Something may change the way to load lib from the other third party packages. The recent bzip2 merge is suspicious.
> > Next step of mine:
> > 
> > 1. Roll back to the last codebase with successful CI run. It is a combination of `devenv` [830335b](https://github.com/solvcon/devenv/commit/830335b844b8e1c274a12d38d208431e1baa1826) and `SOLVCON` [eaac111](https://github.com/solvcon/devenv/commit/eaac1117a9d70770a077252d4d9669ce7077a3f0) to nail down hypothesis A first.
> > 2. Nail down hypothesis B based on the result of the previous step.

**Comment by tai271828** [comment]
Ah, one more issue is coupled in this failure story https://github.com/solvcon/solvcon/issues/252 . It seems that we have to resolve this one prior to moving to "hypothesis B".

**Comment by tai271828** [comment]
The recent plan is:
1. fix https://github.com/solvcon/solvcon/issues/252
2. pin numpy version
3. process hypothesis B

**Comment by tai271828** [comment]
> The recent plan is:
> 
> 1. fix [Version convention should fit PEP400 solvcon#252](https://github.com/solvcon/solvcon/issues/252)

Submitted the pull request https://github.com/solvcon/solvcon/pull/253 for SOLVCON issue #252


> 2. pin numpy version
> 3. process hypothesis B

**Comment by tai271828** [comment]
This task is resolved. The remaining failure will be tracked with https://github.com/solvcon/devenv/issues/101

**Comment by tai271828** [comment]
The title "CI fails" may not tell sufficient information when referring to this issue. Summary of what is fixed to resolve or work around this issue:

- [ ] Worked around numpy version. Tracking root cause here https://github.com/solvcon/devenv/issues/103
- [ ] PEP400 https://github.com/solvcon/devenv/issues/98
- [ ] "Worked around the"[1] build failure of scotch git branch by using tarball. Tracking the git branch here  https://github.com/solvcon/devenv/issues/101

[1] Not really a work-around because we intend to use a stable release tarball. However, it will be great if we can also build our stack with the latest scotch code base.
